// Top 10 destinations for South African travelers
// Difficulty: 1 (easiest) — 5 (hardest)

export const countries = [
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    shortName: "UK",
    flag: "🇬🇧",
    tagline: "Heritage, finance & family reunions",
    difficulty: 4,
    processingTime: "3 – 6 weeks",
    visaType: "Standard Visitor Visa",
    govFee: "From £115",
    requirements: [
      "Valid SA passport (6+ months validity)",
      "Bank statements (last 6 months)",
      "Proof of employment / business",
      "Travel itinerary & accommodation",
      "Tuberculosis test certificate",
    ],
    tips: "The UK is strict on financial evidence. We prepare a bespoke cover letter that pre-empts every ECO concern.",
  },
  {
    slug: "united-states",
    name: "United States",
    shortName: "USA",
    flag: "🇺🇸",
    tagline: "Business, leisure & the American dream",
    difficulty: 5,
    processingTime: "4 – 12 weeks",
    visaType: "B1 / B2 Visitor Visa",
    govFee: "From $185",
    requirements: [
      "DS-160 application",
      "Valid SA passport",
      "Embassy interview (Johannesburg / Cape Town)",
      "Proof of strong ties to SA",
      "Financial documentation",
    ],
    tips: "The US interview is won or lost in 90 seconds. Our mock-interview coaching is the industry benchmark.",
  },
  {
    slug: "germany",
    name: "Germany",
    shortName: "Germany",
    flag: "🇩🇪",
    tagline: "Schengen gateway to 29 countries",
    difficulty: 3,
    processingTime: "15 – 30 days",
    visaType: "Schengen Short-Stay Visa (Type C)",
    govFee: "From €90",
    requirements: [
      "Completed Schengen application",
      "Travel insurance (€30,000+ cover)",
      "Flight & hotel bookings",
      "Bank statements (3 months)",
      "Employment letter",
    ],
    tips: "Germany processes the majority of SA Schengen applications. Precision paperwork is everything.",
  },
  {
    slug: "france",
    name: "France",
    shortName: "France",
    flag: "🇫🇷",
    tagline: "Paris, Provence & the Riviera",
    difficulty: 3,
    processingTime: "15 – 30 days",
    visaType: "Schengen Short-Stay Visa (Type C)",
    govFee: "From €90",
    requirements: [
      "Schengen application form",
      "Travel insurance",
      "Proof of accommodation",
      "Financial means (€65/day)",
      "Return flight booking",
    ],
    tips: "France rewards a clear day-by-day itinerary. We build it for you.",
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    shortName: "Netherlands",
    flag: "🇳🇱",
    tagline: "Business hub of Europe",
    difficulty: 3,
    processingTime: "15 – 21 days",
    visaType: "Schengen Short-Stay Visa (Type C)",
    govFee: "From €90",
    requirements: [
      "Schengen application",
      "Proof of purpose of visit",
      "Financial proof",
      "Travel insurance",
      "Sponsor letter (if applicable)",
    ],
    tips: "The Dutch value clarity. Vague purposes of visit are the #1 reason for refusal.",
  },
  {
    slug: "italy",
    name: "Italy",
    shortName: "Italy",
    flag: "🇮🇹",
    tagline: "La dolce vita awaits",
    difficulty: 3,
    processingTime: "15 – 30 days",
    visaType: "Schengen Short-Stay Visa (Type C)",
    govFee: "From €90",
    requirements: [
      "Schengen application form",
      "Hotel bookings for entire stay",
      "Travel insurance",
      "Bank statements",
      "Employer NOC",
    ],
    tips: "Italy is increasingly strict on first-time applicants. Let us handle the nuances.",
  },
  {
    slug: "uae",
    name: "United Arab Emirates",
    shortName: "UAE",
    flag: "🇦🇪",
    tagline: "Dubai & Abu Dhabi on 72hr turnaround",
    difficulty: 2,
    processingTime: "3 – 5 days",
    visaType: "Tourist Visa (30 or 60 days)",
    govFee: "From AED 370",
    requirements: [
      "Passport copy (6+ months)",
      "Passport-size photo",
      "Return flight ticket",
      "Hotel booking confirmation",
    ],
    tips: "Fastest premium destination. We typically turn these around inside a week.",
  },
  {
    slug: "australia",
    name: "Australia",
    shortName: "Australia",
    flag: "🇦🇺",
    tagline: "Sydney, surfing & second citizenship paths",
    difficulty: 4,
    processingTime: "4 – 8 weeks",
    visaType: "Visitor Visa (Subclass 600)",
    govFee: "From AUD 190",
    requirements: [
      "Online ImmiAccount application",
      "Biometrics",
      "Health & character checks",
      "Financial evidence",
      "Purpose of visit documentation",
    ],
    tips: "Australia is thorough. We front-load the file so case officers have no questions.",
  },
  {
    slug: "canada",
    name: "Canada",
    shortName: "Canada",
    flag: "🇨🇦",
    tagline: "Maple country — study, work & visit",
    difficulty: 4,
    processingTime: "4 – 10 weeks",
    visaType: "Temporary Resident Visa (TRV)",
    govFee: "From CAD 100",
    requirements: [
      "IRCC online application",
      "Biometrics (VFS Pretoria/CT)",
      "Proof of funds",
      "Purpose of travel letter",
      "Ties to home country",
    ],
    tips: "Canada refuses on 'ties' more than anything else. Our letter framework addresses this head-on.",
  },
  {
    slug: "japan",
    name: "Japan",
    shortName: "Japan",
    flag: "🇯🇵",
    tagline: "Tokyo, Kyoto & the land of the rising sun",
    difficulty: 2,
    processingTime: "5 – 10 days",
    visaType: "Temporary Visitor Visa",
    govFee: "From ZAR 580",
    requirements: [
      "Visa application form",
      "Detailed day-by-day itinerary",
      "Flight reservations",
      "Hotel bookings",
      "Bank statements (3 months)",
    ],
    tips: "Japan loves a beautifully prepared itinerary. We craft a document the embassy will remember.",
  },
];

export const getCountry = (slug) => countries.find((c) => c.slug === slug);
